### ISSUE TITLE
CAN Bus support

### ISSUE THREAD

**Issue by chachi** [balena-os/balena-jetson-tx2#124]
As noted [here](https://forums.balena.io/t/use-tx2-can-bus/5167/6) the CAN bus is currently disabled in the TX2 build. It would be great to have the kernel modules included in the build.

**Comment by samiamlabs** [comment]
I would also really appreciate this. I'm working on porting [ros_canopen](https://github.com/JWhitleyAStuff/ros_canopen/tree/crystal-devel) to ROS2 for motor control and would like to be able to use balena-os for our robots with the [RUDI](https://www.siliconhighwaydirect.co.uk/product-p/esg503-22.htm) embedded system.
CAN bus and balena-os for Jetson Xavier would also be nice.

**Comment by floion** [comment]
Hi, we'll be looking into this.
Thanks for the report

**Comment by vicgal** [comment]
Hello,
CAN has been activated for all the tx2 based board in this PR:
https://github.com/balena-os/balena-jetson-tx2/pull/128 . To bring up the CAN interfaces, please install in the container can-utils and libsocketcan. Afterwards all the commands needed to bring up the interfaces are to be issued in the container.

**Comment by abdul1380** [comment]
Hi I am building an applicaiton using rev pi connect and rev con can module.
I am not able to install can-util . As a result not able to use fucntions from can-util
https://github.com/linux-can/can-utils
pip install can-util gives the erorr.
Can you please help

**Comment by floion** [comment]
Hi, can you share your Dockerfile?

**Comment by abdul1380** [comment]
Hi Please see the docker file below.
*# base-image for python on any machine using a template variable,
# see more about dockerfile templates here: https://www.balena.io/docs/learn/develop/dockerfile/
FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-stretch-run

# use `install_packages` if you need to install dependencies,
# for instance if you need git, just uncomment the line below.
RUN pip install can-utils

# Set our working directory
WORKDIR /usr/src/app

# Copy requirements.txt first for better cache on later pushes
COPY requirements.txt requirements.txt

# pip install python deps from requirements.txt on the resin.io build server
RUN pip install -r requirements.txt

# This will copy all files in our root to the working  directory in the container
COPY main.py /usr/src/app

# Enable udevd so that plugged dynamic hardware devices show up in our container.
ENV UDEV=1

# main.py will run when container starts up on the device
CMD ["python","-u","main.py"]`**

**Comment by abdul1380** [comment]
The error that we received is as follows.

![Uploading WhatsApp Image 2023-05-09 at 12.31.50.jpg…]()
